FROM python:3.12-slim
WORKDIR /tests
COPY requirements.txt .
RUN pip install -r requirements.txt && playwright install --with-deps chromium
COPY . .
CMD ["pytest", "--html=/test-results/report.html", "-v"]
